# Site settings
title: Artificial Intelligence and Statistics Conference
email: 
description: > # this means to ignore newlines until "baseurl:"
  This is the website of the AISTATS conference.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aistats.org" # the base hostname & protocol for your site
twitter_username: aistat
github_username:  aistats

# Build settings
markdown: kramdown

# change encoding for the generated output files to utf-8
encoding: utf-8

# Handling Reading
#safe:         false
#include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
