
# Site settings
title: Artificial Intelligence and Statistics Conference
email: aistats2020@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the website of the AISTATS conference.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://www.aistats.org" # the base hostname & protocol for your site
#twitter_username: aistat
github_username:  aistats

github:
  edit: true
  repository: aistats.github.io
TZ: PDT

# Build settings
markdown: kramdown

# change encoding for the generated output files to utf-8
encoding: utf-8

# Handling Reading
#safe:         false
#include:      [".htaccess"]
exclude: [ "accommodation.html", "andreas_krause.html", "david_blei.html", "jeniffer_hill.html", "student_volunteers_application.html" ]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

image:
  file: Palermo.jpg
  width: 400

banner:
  image: TaorminaTheatre.png

credit_card_image: credit.png

conference:
  draft: true # set to True if the programme is draft only.
  logo: logo.jpg
  hide_tentative: true
  proceedings:
    url: http://proceedings.mlr.press/v108/
    show: true
  room: Room
  venue: Teatro Politeama
  venue_url: 
  location: Palermo, Sicily, Italy
  full_name: Artificial Intelligence and Statistics
  name: AISTATS
  year: 2020
  instance: 23rd
  styling: International Conference on
  dates:
  - 2020-06-03
  - 2020-06-05
  submission:
    show: false
    url: http://cmt3.research.microsoft.com/AISTATS2020/ #https://cmt.research.microsoft.com/AISTATS2018/
    name: Microsoft CMT website
  deadlines:
    - name: Submission server open
      type: submission
      text: Tuesday, 17 September 2019
    - name: Paper submission deadline
      type: submission
      text: Tuesday, 8 October 2019 23:59 PDT
    - name: Author response period starts
      date: 2019-11-24
    - name: Author response period ends
      text: Saturday, 30 November 2019 20:59 UTC    
    - name: Paper decision notifications
      date: 2020-01-06
      type: decision
    - name: Registration open
      text: Around mid February 
    # - name: Early registration deadline
    # date: 2019-02-16
    # - name: Regular registration deadline
    # date: 2019-03-16
    - name: Deadline for camera-ready papers
      text: Saturday, 29 February 2020 15:59 UTC  
  chairs:
  - type: Program Chairs
    people:
    - family: Chiappa
      given: Silvia
      url: https://csilviavr.github.io/
      institute: DeepMind
    - family: Calandra
      given: Roberto
      url: https://www.robertocalandra.com/about/
      institute: Facebook AI Research
  - type: Local Chair
    people:
    - family: Lo Presti
      given: Liliana
      url: http://www.diid.unipa.it/cvip/people/lopresti/
      institute: University of Palermo
  - type: Workflow Chairs
    people:
    - family: Trovò
      given: Francesco
      url: https://home.deib.polimi.it/trovo/index.html
      institute: Politecnico di Milano 
  - type: Publication Chair
    people:
    - family: Restelli      
      given: Marcello
      url: http://home.deib.polimi.it/restelli/MyWebSite/index.shtml
      institute: Politecnico di Milano
  - type: Publicity Chair
    people:
    - family: Ricci
      given: Elisa
      url: http://elisaricci.eu/
      institute: University of Trento 
  - type: Family Chair
    people:
    - family: Huszár
      given: Ferenc
      url: https://www.inference.vc/about/
      institute: Twitter
  - type: D&I Chair
    people:
    - family: Belgrave
      given: Danielle 
      url: https://www.imperial.ac.uk/people/d.belgrave
      institute: Microsoft Research Cambridge
  - type: Sponsorship Chair
    people:
    - family: Palla
      given: Konstantina 
      url: https://www.microsoft.com/en-us/research/people/kopalla/
      institute: Microsoft Research Cambridge

previous_meeting:
  name:
  url:
