
# Site settings
title: Artificial Intelligence and Statistics Conference
email: aistats2019@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the website of the AISTATS conference.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://www.aistats.org" # the base hostname & protocol for your site
#twitter_username: aistat
github_username:  aistats

github:
  edit: true
  repository: aistats.github.io
TZ: PDT

# Build settings
markdown: kramdown

# change encoding for the generated output files to utf-8
encoding: utf-8

# Handling Reading
#safe:         false
#include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

image:
  file: fukusyu-en_zenkei1L.jpg
  width: 400

banner:
  image: banner.png

credit_card_image: credit.png

conference:
  draft: true # set to True if the programme is draft only.
  logo: logo.jpg
  hide_tentative: true
  proceedings:
    url: 
    show: false
  room: Room
  venue: LOISIR Hotel Naha (3-2-1 Nishi, Naha-shi, Okinawa, 900-0036, Japan)
  venue_url: http://www.solarehotels.com/en/hotel/okinawa/loisir-naha/?_ga=2.26044093.18688415.1504828500-1079017007.1493258416
  location: Naha, Okinawa, Japan
  full_name: Artificial Intelligence and Statistics
  name: AISTATS
  year: 2019
  instance: 22nd
  styling: International Conference on
  dates:
  - 2019-04-16
  - 2019-04-18
  submission:
    url: #https://cmt.research.microsoft.com/AISTATS2018/
    name: Microsoft CMT website
  deadlines:
    - name: Paper submission deadline
      type: submission
      time: 2018-10-05 23:59:00
    - name: Author feedback deadline
      date: 2018-11-20
    - name: Paper decision notifications
      date: 2018-12-24
      type: decision
    - name: Camera ready (for accepted papers) deadline
      date: 2019-03-16
    #  deadlines:  
    #  - name: Paper submission deadline
    #    type: submission
    #    time: 2017-10-13T23:59:00+0
    #  - name: Initial reviews available
    #    date: 2017-11-22
    #  - name: Author feedback deadline
    #    date: 2017-11-29
    #  - name: Paper decision notifications
    #    date: 2017-12-22
    #    type: decision
    #  - name: Camera ready (for accepted papers) deadline
    #    date: 2018-02-20
    #    type: camera-ready
    #  - name: Early registration deadline
    #    date: 2018-01-31
    #  - name: Regular registration deadline
    #    date: 2018-04-11
  chairs:
  - type: Program Chairs
    people:
    - family: Chaudhuri
      given: Kamalika
      url: http://cseweb.ucsd.edu/~kamalika/
      institute: University of California, San Diego
    - family: Sugiyama
      given: Masashi
      url: http://www.ms.k.u-tokyo.ac.jp/sugi/
      institute: RIKEN and University of Tokyo
  - type: Local Chair
    people:
    - family: Takeuchi
      given: Ichiro
      url: http://www-als.ics.nitech.ac.jp/~takeuchi/
      institute: Nagoya Institute of Technology and RIKEN
  - type: Workflow Chairs
    people:
    - family: Foulds
      given: James
      url: http://jfoulds.informationsystems.umbc.edu/
      institute: University of Maryland, Baltimore County
    - family: Yamada
      given: Makoto
      url: http://www.makotoyamada-ml.com/
      institute: Kyoto University and RIKEN
  - type: Publication Chairs
    people:
    - family: Sarkar
      given: Purna
      url: https://psarkar.github.io/
      institute: University of Texas at Austin
    - family: Takeda
      given: Akiko
      url: https://www.opt.mist.i.u-tokyo.ac.jp/~takeda/profile-e.html
      institute: University of Tokyo and RIKEN
  - type: Publicity Chair
    people:
    - family: Hsu
      given: Daniel
      url: http://www.cs.columbia.edu/~djhsu/ 
      institute: Columbia University
      #  - type: Workflow Chairs
      #    people:
      #    - family: Crowley
      #      given: Elliot
      #      url: http://homepages.inf.ed.ac.uk/ecrowley/
      #      institute: School of Informatics, University of Edinburgh
#    - family: Alfeld
#      given: Scott
#      url: http://www.cs.wisc.edu/~salfeld
#      institute: Department of Computer Sciences, University of Wisconsin -- Madison
#    - family:  Ruiz 
#      given: Francisco
#      url: http://franrruiz.github.io/
#      institute: Columbia University
#  - type: Publicity Chairs
#    people: 
#    - family: Antoniou
#      given: Antreas
#      url: https://www.inf.ed.ac.uk/people/students/Antreas_Antoniou.html
#      institute: School of Informatics, University of Edinburgh
#  - type: Publication Chair
#    people:
#    - family:
#      given: 
#      url: 
#      institute: 
#  - type: Fundraising Chair
#    people: 
#    - family: Lacoste-Julien
#      given: Simon
#      url: http://www.di.ens.fr/~slacoste/
#      institute: Universit&eacute; de Montr&eacute;al
#  - type: Proceedings Chair
#    people:
#    - family: Azencott
#      given: Chloe-Agathe
#      url: http://cazencott.info/
#      institute: MINES Paris Tech
#  - type: Conference Admins
#    people: 
#    - family: Smith
#      given: Karen
#    - family: Pregibon
#      given: Daryl
#  - type: Area Chairs
#    people:
#    - family: Adams
#      given: Ryan
#      url: rpa@seas.harvard.edu
#      institute: Harvard University
#    - family: Artes
#      given: Antonio
#      url: antonio@tsc.uc3m.es
#      institute: UC3M
#    - family: Barber
#      given: David
#      url: d.barber@cs.ucl.ac.uk
#      institute: UCL
#    - family: Bonilla
#      given: Edwin
#      url: e.bonilla@unsw.edu.au
#      institute: University of New South Wales
#    - family: Carreira-Perpinan
#      given: Miguel
#      url: mcarreira-perpinan@ucmerced.edu
#      institute: UC Merced
#    - family: Cesa-Bianchi
#      given: Nicolò
#      url: nicolo.cesa-bianchi@unimi.it
#      institute: University of Milan
#    - family: Chiappa
#      given: Silvia
#      url: chiappa.silvia@gmail.com
#      institute: DeepMind
#    - family: Choromanska
#      given: Anna
#      url: ac5455@nyu.edu
#      institute: NYU
#    - family: Cohen
#      given: Shay
#      url: scohen@inf.ed.ac.uk
#      institute: University of Edinburgh
#    - family: Crammer
#      given: Koby
#      url: koby@ee.technion.ac.il
#      institute: Technion
#    - family: Cuturi
#      given: Marco
#      url: marco.cuturi@ensae.fr
#      institute: ENSAE/CREST
#    - family: Dai
#      given: Andrew
#      url: adai@google.com
#      institute: Google Brain
#    - family: Deisenroth
#      given: Mark
#      url: m.deisenroth@imperial.ac.uk
#      institute: Imperial College London
#    - family: Doshi-Velez
#      given: Finale
#      url: finale@seas.harvard.edu
#      institute: Harvard University
#    - family: Duvenaud
#      given: David
#      url: duvenaud@cs.toronto.edu
#      institute: University of Toronto
#    - family: Flach
#      given: Peter
#      url: peter.flach@bristol.ac.uk
#      institute: University of Bristol
#    - family: Foti
#      given: Nicholas
#      url: nfoti@uw.edu
#      institute: University of Washington
#    - family: Gal
#      given: Yarin
#      url: yg279@cam.ac.uk
#      institute: University of Cambridge
#    - family: Gomez Rodriguez
#      given: Manuel
#      url: manuelgr@mpi-sws.org
#      institute: Max Planck Institute for Software Systems
#    - family: Goodman
#      given: Noah
#      url: ngoodman@stanford.edu
#      institute: Stanford University
#    - family: Graham
#      given: Matthew
#      url: m.m.graham@ed.ac.uk
#      institute: University of Edinburgh
#    - family: Gutmann
#      given: Michael
#      url: michael.gutmann@ed.ac.uk
#      institute: University of Edinburgh
#    - family: Harmeling
#      given: Stefan
#      url: harmeling@hhu.de
#      institute: HHU
#    - family: Heess
#      given: Nicolas
#      url: heess@google.com
#      institute: DeepMind
#    - family: Heller
#      given: Katherine
#      url: kheller@stat.duke.edu
#      institute: Duke University
#    - family: Hennig
#      given: Philipp
#      url: ph@tue.mpg.de
#      institute: University of Tübingen
#    - family: Hernandez-Lobato
#      given: Jose Miguel
#      url: jmh233@cam.ac.uk
#      institute: University of Cambridge
#    - family: Hernández-Lobato
#      given: Daniel
#      url: daniel.hernandez@uam.es
#      institute: Autonoma
#    - family: Hoffman
#      given: Matthias
#      url: matt@matthewdhoffman.com
#      institute: Google
#    - family: Holmes
#      given: Chris
#      url: cholmes@stats.ox.ac.uk
#      institute: University of Oxford
#    - family: Husmeier
#      given: Dirk
#      url: dirk.husmeier@glasgow.ac.uk
#      institute: University of Glasgow
#    - family: Jaggi
#      given: Martin
#      url: martin.jaggi@epfl.ch
#      institute: EPFL
#    - family: Jaitly
#      given: Navdeep
#      url: ndjaitly@google.com
#      institute: Google
#    - family: Joulin
#      given: Armand Joulin
#      url: ajoulin@fb.com
#      institute: Facebook
#    - family: Kaski
#      given: Samuel
#      url: samuel.kaski@aalto.fi
#      institute: Aalto University
#    - family: Khardon
#      given: Roni
#      url: roni@cs.tufts.edu
#      institute: Tufts University
#    - family: Lacoste-Julien
#      given: Simon
#      url: simon.lacoste-julien@umontreal.ca
#      institute: Université de Montréal
#    - family: Lozano
#      given: Aurelie
#      url: aclozano@us.ibm.com
#      institute: IBM
#    - family: Mohamed
#      given: Shakir
#      url: shakir.mohamed@gmail.com
#      institute: DeepMind
#    - family: Mukherjee
#      given: Sayan Mukherjee
#      url: sayan@stat.duke.edu
#      institute: Duke University
#    - family: Nowozin
#      given: Sebastian
#      url: sebastian.nowozin@microsoft.com
#      institute: Microsoft
#    - family: Osborne
#      given: Michael
#      url: mosb@robots.ox.ac.uk
#      institute: University of Oxford
#    - family: Ranganath
#      given: Rajesh
#      url: rajeshr@cs.princeton.edu
#      institute: Princeton University
#    - family: Rao
#      given: Vinayak
#      url: varao@purdue.edu
#      institute: Purdue University
#    - family: Sabourin
#      given: Anne
#      url: anne.sabourin@telecom-paristech.fr
#      institute: Telecom ParisTech
#    - family: Santos-Rodriguez
#      given: Raul
#      url: enrsr@bristol.ac.uk
#      institute: University of Bristol
#    - family: Särkkä
#      given: Simo
#      url: simo.sarkka@aalto.fi
#      institute: Aalto University
#    - family: Sha
#      given: Fei
#      url: feisha@usc.edu
#      institute: UCLA
#    - family: Shlens
#      given: Jon
#      url: shlens@google.com
#      institute: Google
#    - family: Szabo
#      given: Zoltan
#      url: zoltan.szabo@polytechnique.edu
#      institute: École Polytechnique
#    - family: Titsias
#      given: Michalis
#      url: mtitsias@aueb.gr
#      institute: AUEB
#    - family: Urner
#      given: Ruth
#      url: ruth.urner@tuebingen.mpg.de
#      institute: Max Planck Institute for Intelligent Systems
#    - family: Valera
#      given: Isabel
#      url: miv24@cam.ac.uk
#      institute: University of Cambridge
#    - family: Weller
#      given: Adrian
#      url: adrian.weller@eng.cam.ac.uk
#      institute: University of Cambridge
#    - family: Winther
#      given: Ole
#      url: olwi@dtu.dk
#      institute: DTU
#    - family: Zhu
#      given: Zhanxing
#      url: zhanxing.zhu@pku.edu.cn
#      institute: Peking University


  sponsors:
#  - name: Disney Research
#    logo: dr-logo-red.png
#    url: http://www.disneyresearch.com
#    width: 250
#  - name: Google
#    url: http://research.google.com
#    logo: google.png
#    width: 250
#  - name: Netflix
#    url: http://www.netflix.com
#    logo: netflix.png
#    width: 250
#  - name: Tencent
#    url: http://www.tencent.com
#    logo: tencent.png
#    width: 250
#  - name: Springer
#    logo: springer.png
#    width: 300
#    url: http://www.springer.com
#  - name: Microsoft Research
#    logo: MSFT_logo_rgb_C-Gray.png
#    url: http://research.microsoft.com
#    width: 300

previous_meeting:
  name:
  url:
